changelog:
  exclude:
    labels:
      - '*'
  categories:
    - title: 'New features'
      labels:
        - feature
        - enhancement
    - title: 'Bug fixes'
      labels:
        - fix
        - bug
